In [26]:
import numpy as np
import pandas as pd
from sklearn import datasets
import sklearn.metrics as sm
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
print("IRIS DATA:\n", iris.data)
print("\n IRIS TARGET NAMES:",iris.target_names)
X = pd.DataFrame(iris.data)
X.columns = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width']
y = pd.DataFrame(iris.target)
y.columns = ['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

data = pd.concat([X_train, y_train], axis=1)

#--------------------------------------------------------------------------------------retrieve_values
n_0 = data['Target'][data['Target'] == 0].count()
n_1 = data['Target'][data['Target'] == 1].count()
n_2 = data['Target'][data['Target'] == 2].count()
total = len(data)

#no of 0,1,2 classes divided by the total rows 
p_0 = n_0 / total    
p_1 = n_1 / total   
p_2 = n_2 / total

# group the data by target & calculate the means of each feature
data_means = data.groupby('Target').mean()
print('\n Dataset Mean\n', data_means)

# calculate the data variance 
# variance = summation of((mean - x) ** 2) / n 
data_variance = data.groupby('Target').var()
print('\n Dataset Variance\n', data_variance)

#--------------------------------------------------------------------------------------class 0 variables
    
#mean for class 0 
class_0_SL_mean = data_means['Sepal_Length'][data_means.index == 0].values[0]
class_0_SW_mean =  data_means['Sepal_Width'][data_means.index == 0].values[0]
class_0_PL_mean =  data_means['Petal_Length'][data_means.index == 0].values[0]
class_0_PW_mean =  data_means['Petal_Width'][data_means.index == 0].values[0]

#variance for class 0 
class_0_SL_variance = data_variance['Sepal_Length'][data_variance.index == 0].values[0] 
class_0_SW_variance = data_variance['Sepal_Width'][data_variance.index == 0].values[0] 
class_0_PL_variance = data_variance['Petal_Length'][data_variance.index == 0].values[0] 
class_0_PW_variance = data_variance['Petal_Width'][data_variance.index == 0].values[0] 

#--------------------------------------------------------------------------------------class 1 variables

#mean for class 1 
class_1_SL_mean = data_means['Sepal_Length'][data_means.index == 1].values[0]
class_1_SW_mean =  data_means['Sepal_Width'][data_means.index == 1].values[0]
class_1_PL_mean =  data_means['Petal_Length'][data_means.index == 1].values[0]
class_1_PW_mean =  data_means['Petal_Width'][data_means.index == 1].values[0]

#variance for class 1 
class_1_SL_variance = data_variance['Sepal_Length'][data_variance.index == 1].values[0] 
class_1_SW_variance = data_variance['Sepal_Width'][data_variance.index == 1].values[0] 
class_1_PL_variance = data_variance['Petal_Length'][data_variance.index == 1].values[0] 
class_1_PW_variance = data_variance['Petal_Width'][data_variance.index == 1].values[0] 

#--------------------------------------------------------------------------------------class 2 variables

#mean for class 2 
class_2_SL_mean = data_means['Sepal_Length'][data_means.index == 2].values[0]
class_2_SW_mean =  data_means['Sepal_Width'][data_means.index == 2].values[0]
class_2_PL_mean =  data_means['Petal_Length'][data_means.index == 2].values[0]
class_2_PW_mean =  data_means['Petal_Width'][data_means.index == 2].values[0]

#variance for class 2 
class_2_SL_variance = data_variance['Sepal_Length'][data_variance.index == 2].values[0] 
class_2_SW_variance = data_variance['Sepal_Width'][data_variance.index == 2].values[0] 
class_2_PL_variance = data_variance['Petal_Length'][data_variance.index == 2].values[0] 
class_2_PW_variance = data_variance['Petal_Width'][data_variance.index == 2].values[0] 


def p_x_given_y(x, mean_y, variance_y):
# a function which calculates p(x|y)
   
    #input the arguments into a probability density function
    p = 1/( np.sqrt(2*np.pi*variance_y) )  *  np.exp( (-(x-mean_y) ** 2)/(2*(variance_y **2)))
    return p


def result(): 
    test_data=pd.concat([X_test, y_test], axis=1)
    pred=[]
    print("\n Test Data:\n",test_data)
    for rowIndex, row in test_data.iterrows():
        #print('\nTest Instance {0}: \n '. format(rowIndex),row)

        prob_0 = p_0 * \
                p_x_given_y(row['Sepal_Length'], class_0_SL_mean, class_0_SL_variance) * \
                p_x_given_y(row['Sepal_Width'], class_0_SW_mean, class_0_SW_variance) * \
                p_x_given_y(row['Petal_Length'], class_0_PL_mean, class_0_PL_variance) * \
                p_x_given_y(row['Petal_Width'], class_0_PW_mean, class_0_PW_variance)
        #print('\nProbability of class 0:', prob_0)

        prob_1 = p_1 * \
                p_x_given_y(row['Sepal_Length'], class_1_SL_mean, class_1_SL_variance) * \
                p_x_given_y(row['Sepal_Width'], class_1_SW_mean, class_1_SW_variance) * \
                p_x_given_y(row['Petal_Length'], class_1_PL_mean, class_1_PL_variance) * \
                p_x_given_y(row['Petal_Width'], class_1_PW_mean, class_1_PW_variance)
        #print('\nProbability of class 1:', prob_1)
        
        prob_2 = p_2 * \
                p_x_given_y(row['Sepal_Length'], class_2_SL_mean, class_2_SL_variance) * \
                p_x_given_y(row['Sepal_Width'], class_2_SW_mean, class_2_SW_variance) * \
                p_x_given_y(row['Petal_Length'], class_2_PL_mean, class_2_PL_variance) * \
                p_x_given_y(row['Petal_Width'], class_2_PW_mean, class_2_PW_variance)
        #print('\nProbability of class 2:', prob_2)
        
        if (prob_0 >= prob_1) and (prob_0 >= prob_2):
            pred.append(0)
        elif (prob_1 >= prob_0) and (prob_1 >= prob_2):
            pred.append(1)
        else:
            pred.append(2)
         
    print("\nAccuracy of the classifier: {:.2f}".format(sm.accuracy_score(y_test, pred)))
    
result()

IRIS DATA:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
